on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.16.1'

    - name: Check vet
      run: |
        go vet ./...

    - name: Check unit test
      run: |
            sudo go test ./... -coverprofile coverage.out -covermode count
            sudo go tool cover -func coverage.out

    - name: Check coverage
      env:
          TESTCOVERAGE_THRESHOLD: 40
      run: |
            echo "Minimum coverage: $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage: $totalCoverage %"
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust percentage to a lower value."
                echo "Failed"
                exit 1
            fi
    
    - name: golang lint
      uses: golangci/golangci-lint-action@v2
      with:
        args: --issues-exit-code 1 --timeout 15m