on:
  pull_request:
    branches: [ main ]

jobs:
  checker:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17.1'

    - name: Setup Golang
      run: |
            go version
            curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.50.1

    - name: Check vet
      run: |
            go vet ./...

    - name: Check lint
      run: |
            golangci-lint run --issues-exit-code 0 --timeout 15m

    - name: Check unit test
      run: |
            sudo go test ./... -coverprofile coverage.out -covermode count
            sudo go tool cover -func coverage.out

    - name: Check coverage
      env:
          TESTCOVERAGE_THRESHOLD: 30
      run: |
            echo "Minimum coverage: $TESTCOVERAGE_THRESHOLD %"
            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
            echo "Current test coverage: $totalCoverage %"
            echo "COVERAGE=$totalCoverage" >> $GITHUB_ENV
            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print ($1 >= $2)}') )); then
                echo "OK"
            else
                echo "Current test coverage is below threshold. Please add more unit tests or adjust percentage to a lower value."
                echo "Failed"
                exit 1
            fi
      - name: Comment a pull_request
        uses: mb2dev/github-action-comment-pull-request@1.0.0
        with:
          message: "COVERAGE = ${{ env.COVERAGE }}%\n Thankyou!"
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

    # - name: Create the Badge
    #   uses: schneegans/dynamic-badges-action@v1.0.0
    #   with:
    #     auth: ${{ secrets.GIST_SECRET }}
    #     gistID: 93bfa9c6e08a21154f9d6a56da5304ee
    #     filename: covbadge.json
    #     label: Coverage
    #     message: ${{ env.COVERAGE }}
    #     namedLogo: jest
    #     color: blue
    #     logoColor: lightblue